add missing str to bytes conversion for Python3
Using Python3, Gearman unexpectedly closed the socket with a client when typing the 'workers' command.

gearman-debug.log:
    File "/usr/local/lib/python3.5/dist-packages/gear/__init__.py", line 3250, in handleWorkers
      (fd, ip, client_id.decode('utf8'),
  AttributeError: 'str' object has no attribute 'decode'

Change-Id: I610bd44c76a0e52f8d4e8f24c82c636d4ebef0ae